export function creativeStudioHtml(): string {
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>ATTHA'S Creative Studio</title>
<style>
  :root{
    color-scheme:dark;
    --bg:#101112;--panel:#17191b;--panel2:#1d2023;--line:#2c3034;--text:#f6f1e8;--muted:#a6a6a6;
    --accent:#ffd21a;--danger:#ff6b6b;--ok:#65d58a;--warn:#f4bd53;--red:#b50008;--radius:12px;
  }
  *{box-sizing:border-box} html,body{margin:0;height:100%;font-family:Inter,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;background:var(--bg);color:var(--text)}
  button,input,select,textarea{font:inherit} button{cursor:pointer}
  .app{height:100vh;display:grid;grid-template-rows:58px 1fr 32px;overflow:hidden}
  .topbar{display:flex;align-items:center;gap:10px;padding:0 14px;border-bottom:1px solid var(--line);background:#141618}
  .brandmark{font-weight:900;letter-spacing:.4px;margin-right:8px}.brandmark span{color:var(--accent)}
  .topbar .spacer{flex:1}.topbar button,.topbar select{height:34px;border:1px solid var(--line);border-radius:8px;background:var(--panel2);color:var(--text);padding:0 11px}
  .topbar button.primary{background:var(--accent);color:#171717;border-color:var(--accent);font-weight:800}.topbar button:disabled{opacity:.45;cursor:not-allowed}
  .workspace{display:grid;grid-template-columns:300px minmax(420px,1fr) 290px;min-height:0}
  .left,.right{background:var(--panel);overflow:auto}.left{border-right:1px solid var(--line)}.right{border-left:1px solid var(--line)}
  .tabs{display:grid;grid-template-columns:repeat(4,1fr);position:sticky;top:0;z-index:5;background:var(--panel);border-bottom:1px solid var(--line)}
  .tab{border:0;background:transparent;color:var(--muted);padding:12px 4px;font-size:12px}.tab.active{color:var(--text);box-shadow:inset 0 -2px 0 var(--accent)}
  .panel{padding:14px}.hidden{display:none!important}.section{border-bottom:1px solid var(--line);padding-bottom:14px;margin-bottom:14px}.section:last-child{border-bottom:0}
  h2,h3,p{margin-top:0}h2{font-size:16px;margin-bottom:10px}h3{font-size:12px;text-transform:uppercase;letter-spacing:.08em;color:var(--muted);margin-bottom:9px}
  .field{display:grid;gap:5px;margin-bottom:10px}.field label{font-size:12px;color:#c9c9c9}.field input,.field select,.field textarea{width:100%;border:1px solid var(--line);background:#111315;color:var(--text);border-radius:8px;padding:9px 10px;outline:none}.field textarea{min-height:68px;resize:vertical}.field input:focus,.field select:focus,.field textarea:focus{border-color:#686e73}
  .row{display:flex;gap:8px}.row>*{flex:1}.checks{display:flex;flex-wrap:wrap;gap:6px}.chip{display:flex;align-items:center;gap:5px;border:1px solid var(--line);border-radius:999px;padding:5px 8px;font-size:11px;background:#121416}.chip input{margin:0}
  .action{width:100%;border:0;border-radius:8px;background:var(--accent);color:#171717;font-weight:800;padding:10px}.secondary{border:1px solid var(--line);border-radius:8px;background:var(--panel2);color:var(--text);padding:8px 10px}.danger{border-color:#6b3434!important;color:#ffb0b0!important}
  .note{font-size:11px;line-height:1.45;color:var(--muted)}.pill{display:inline-flex;border-radius:999px;padding:3px 7px;font-size:10px;font-weight:800;background:#2b2e31;color:#ddd}.pill.ok{background:#163923;color:#9cebb5}.pill.warn{background:#4a3515;color:#ffd689}.pill.block{background:#4b1f21;color:#ffb0b0}
  .canvas-shell{position:relative;min-height:0;overflow:hidden;background:#0b0c0d;display:flex;align-items:center;justify-content:center}
  .canvas-grid{position:absolute;inset:0;background-image:linear-gradient(#ffffff08 1px,transparent 1px),linear-gradient(90deg,#ffffff08 1px,transparent 1px);background-size:22px 22px;pointer-events:none}
  #artboardWrap{position:relative;max-width:88%;max-height:88%;filter:drop-shadow(0 22px 50px #000b)}
  #artboard{display:block;max-width:100%;max-height:calc(100vh - 140px);background:#fff;touch-action:none;user-select:none}
  .emptyCanvas{position:absolute;text-align:center;color:var(--muted);max-width:430px}.emptyCanvas strong{display:block;color:var(--text);font-size:22px;margin-bottom:8px}
  .layer-row{display:grid;grid-template-columns:24px 1fr 26px 26px;gap:5px;align-items:center;border:1px solid transparent;border-radius:8px;padding:6px;margin-bottom:3px}.layer-row:hover{background:#1e2124}.layer-row.selected{background:#24282c;border-color:#40464c}.layer-name{overflow:hidden}.layer-name strong{display:block;font-size:12px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.layer-name small{color:var(--muted);font-size:10px}.iconbtn{border:0;background:transparent;color:#bbb;padding:3px}.iconbtn:hover{color:#fff}
  .prop-grid{display:grid;grid-template-columns:1fr 1fr;gap:7px}.prop-grid .field{margin:0}.prop-grid input{padding:7px 8px}.toolbar-row{display:flex;gap:6px;margin:8px 0}.toolbar-row button{flex:1}
  .qa-list{display:grid;gap:6px}.qa-item{border-left:3px solid var(--line);background:#121416;padding:8px;border-radius:5px;font-size:11px;line-height:1.4}.qa-item.HIGH{border-left-color:var(--danger)}.qa-item.MEDIUM{border-left-color:var(--warn)}.qa-item.LOW{border-left-color:#6e8ba7}
  .asset-card{border:1px solid var(--line);border-radius:8px;padding:8px;margin-bottom:6px}.asset-card strong{font-size:11px;display:block}.asset-card small{color:var(--muted);font-size:10px}
  .statusbar{display:flex;align-items:center;gap:14px;padding:0 10px;background:#121416;border-top:1px solid var(--line);color:var(--muted);font-size:10px}.statusbar .spacer{flex:1}.status-dot{width:6px;height:6px;border-radius:50%;background:#777}.status-dot.ok{background:var(--ok)}.status-dot.error{background:var(--danger)}
  .modal{position:fixed;inset:0;background:#000a;display:flex;align-items:center;justify-content:center;z-index:50;padding:20px}.modal-card{width:min(720px,96vw);max-height:88vh;overflow:auto;background:var(--panel);border:1px solid #3b4045;border-radius:14px;box-shadow:0 30px 90px #000;padding:18px}.truth-card{padding:12px;border:1px solid var(--line);border-radius:9px;margin-bottom:9px}.truth-card p{font-size:12px;color:#ccc;line-height:1.45;margin-bottom:7px}.modal-actions{display:flex;justify-content:flex-end;gap:8px;position:sticky;bottom:0;padding-top:12px;background:linear-gradient(transparent,var(--panel) 30%)}
  .progress{display:grid;gap:7px;margin-top:10px}.progress-item{display:flex;align-items:center;gap:8px;font-size:11px;color:var(--muted)}.progress-item.done{color:#bdeecb}.progress-item.active{color:#fff}.dot{width:8px;height:8px;border-radius:50%;background:#555}.done .dot{background:var(--ok)}.active .dot{background:var(--accent);box-shadow:0 0 0 4px #ffd21a22}
  @media(max-width:1050px){.workspace{grid-template-columns:260px 1fr}.right{position:absolute;right:0;top:58px;bottom:32px;width:280px;z-index:20;box-shadow:-10px 0 30px #0008}.workspace.right-closed .right{display:none}}
</style>
</head>
<body>
<div class="app">
  <header class="topbar">
    <div class="brandmark">ATTHA'S <span>Creative Studio</span></div>
    <button id="undoBtn" disabled>Undo</button><button id="redoBtn" disabled>Redo</button>
    <button id="guidesBtn">Guides: On</button>
    <div class="spacer"></div>
    <span id="qaBadge" class="pill">No design</span>
    <button id="qaBtn" disabled>Final QA</button>
    <select id="exportPreset"><option value="standard">Standard</option><option value="high-resolution">High Resolution</option><option value="4k">4K</option></select>
    <button id="exportBtn" class="primary" disabled>Export PNG</button>
  </header>
  <main id="workspace" class="workspace">
    <aside class="left">
      <div class="tabs">
        <button class="tab active" data-tab="brief">Brief</button><button class="tab" data-tab="layers">Layers</button><button class="tab" data-tab="assets">Assets</button><button class="tab" data-tab="ai">AI</button>
      </div>
      <section id="tab-brief" class="panel tabpanel">
        <div class="section">
          <h2>Creative Brief</h2>
          <p class="note">Structured intake feeds the existing truth-confirmation and governed production pipeline. You do not need to write a production prompt.</p>
          <div class="field"><label>Brand</label><select id="brandId"><option value="ATTHAS_BURGER">ATTHA'S Burger</option><option value="ATTHAS_RESTAURANT">ATTHA'S Restaurant</option></select></div>
          <div class="field"><label>Branch</label><select id="branchId"></select></div>
          <div class="field"><label>Campaign goal</label><select id="goal"><option>Promote product</option><option>Product launch</option><option>Special offer</option><option>Brand awareness</option><option>Engagement</option><option>Seasonal campaign</option><option>Dine-in campaign</option><option>Delivery campaign</option></select></div>
          <div class="field"><label>Campaign description</label><textarea id="description" placeholder="Promote the Chicken Tikka Wrap with a premium, energetic treatment."></textarea></div>
          <div class="field"><label>Product / menu item</label><input id="productId" placeholder="Chicken Tikka Wrap" /></div>
          <div class="field"><label>Audience</label><input id="audience" value="families, students, Gen Z" /></div>
          <div class="field"><label>Vibe</label><div class="checks" id="vibeChecks"></div></div>
          <div class="field"><label>Output format</label><select id="formatPreset"><option value="instagram-portrait">Instagram Portrait — 4:5</option><option value="instagram-square">Instagram Square — 1:1</option><option value="instagram-story">Instagram Story — 9:16</option><option value="facebook-post">Facebook Post — 4:5</option></select></div>
          <div class="row"><div class="field"><label>Sales channel</label><select id="salesChannel"><option value="">Not specified</option><option>DINE_IN</option><option>TAKEAWAY</option><option>UBER_EATS</option><option>PICKME</option></select></div><div class="field"><label>Mode</label><select id="productionMode"><option value="DRAFT">Draft</option><option value="FINAL">Final + QA</option></select></div></div>
          <div class="checks" style="margin-bottom:10px"><label class="chip"><input type="checkbox" id="showPrice" /> Price</label><label class="chip"><input type="checkbox" id="showProduct" checked /> Product name</label><label class="chip"><input type="checkbox" id="showBranch" /> Branch</label><label class="chip"><input type="checkbox" id="showCta" checked /> CTA</label></div>
          <div class="field"><label>Optional approved base/product image</label><input id="baseImage" type="file" accept="image/png,image/jpeg,image/webp" /></div>
          <div class="checks" style="margin-bottom:10px"><label class="chip"><input type="checkbox" id="approvedAds" /> Approved for ads</label><label class="chip"><input type="checkbox" id="appearanceVerified" /> Appearance verified</label><label class="chip"><input type="checkbox" id="ingredientVerified" /> Ingredient match verified</label></div>
          <button id="prepareBtn" class="action">Prepare Creative</button>
          <div id="generationProgress" class="progress hidden"></div>
        </div>
        <div class="section">
          <h3>Open existing campaign</h3>
          <div class="field"><select id="campaignSelect"><option value="">Choose a completed campaign…</option></select></div>
          <button id="openCampaignBtn" class="secondary" style="width:100%">Open in Studio</button>
        </div>
      </section>
      <section id="tab-layers" class="panel tabpanel hidden"><h2>Layers</h2><div id="layersList"></div></section>
      <section id="tab-assets" class="panel tabpanel hidden"><h2>Assets</h2><div id="assetsList"></div></section>
      <section id="tab-ai" class="panel tabpanel hidden">
        <h2>AI Layer Tools</h2><p class="note">AI operations are scoped to the selected layer. Manual geometry changes never call a model.</p>
        <div class="field"><label>Edit instruction</label><textarea id="aiInstruction" placeholder="Make this headline shorter and more premium."></textarea></div>
        <button id="aiApplyBtn" class="action" disabled>Apply to Selected Layer</button>
        <div class="toolbar-row"><button class="secondary aiPreset" data-instruction="Shorten this while preserving the core message.">Shorten</button><button class="secondary aiPreset" data-instruction="Make this feel more premium and restrained.">Premium</button></div>
        <p class="note">Verified product visuals, price layers, logos, and unsegmented composite backgrounds are protected from destructive AI editing.</p>
      </section>
    </aside>
    <section class="canvas-shell">
      <div class="canvas-grid"></div>
      <div id="emptyCanvas" class="emptyCanvas"><strong>Build a campaign, then design it.</strong>Complete the Creative Brief or open a previously rendered campaign. The result will appear here as editable native layers.</div>
      <div id="artboardWrap" class="hidden"><svg id="artboard" xmlns="http://www.w3.org/2000/svg"></svg></div>
    </section>
    <aside class="right">
      <div class="panel">
        <h2>Properties</h2><div id="propertiesEmpty" class="note">Select a layer to inspect and edit it.</div><div id="properties" class="hidden"></div>
        <div class="section" style="margin-top:16px"><h3>QA</h3><div id="qaSummary" class="note">Run Final QA to validate truth, brand and layout.</div><div id="qaList" class="qa-list" style="margin-top:8px"></div></div>
      </div>
    </aside>
  </main>
  <footer class="statusbar"><span id="statusDot" class="status-dot"></span><span id="statusText">Starting Creative Studio…</span><span class="spacer"></span><span id="designMeta">No design loaded</span></footer>
</div>
<div id="truthModal" class="modal hidden"><div class="modal-card"><h2>Confirm Publishing Facts</h2><p class="note">The AI cannot proceed until every task-relevant publishing fact is confirmed. Stored business truth remains authoritative.</p><div id="truthQuestions"></div><div class="modal-actions"><button id="cancelTruth" class="secondary">Cancel</button><button id="confirmTruth" class="action" style="width:auto">Confirm & Generate</button></div></div></div>
<script>
(function(){
  'use strict';
  var state={bootstrap:null,uiBootstrap:null,prepared:null,snapshot:null,project:null,selectedLayerId:null,drag:null,guides:true,brief:null};
  var $=function(id){return document.getElementById(id)};
  function setStatus(message,type){$('statusText').textContent=message;$('statusDot').className='status-dot'+(type==='ok'?' ok':type==='error'?' error':'');}
  async function api(path,options){var response=await fetch(path,Object.assign({headers:{'content-type':'application/json'}},options||{}));var data=await response.json();if(!response.ok)throw new Error(data.error||('HTTP '+response.status));return data;}
  function esc(value){return String(value==null?'':value).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c];});}
  function formatPreset(value){if(value==='instagram-square')return {preset:value,width:1080,height:1080,channel:'instagram',assetType:'poster'};if(value==='instagram-story')return {preset:value,width:1080,height:1920,channel:'instagram',assetType:'story'};if(value==='facebook-post')return {preset:value,width:1080,height:1350,channel:'facebook',assetType:'poster'};return {preset:'instagram-portrait',width:1080,height:1350,channel:'instagram',assetType:'poster'};}
  function campaignType(goal,product){var g=goal.toLowerCase();if(g.indexOf('offer')>=0)return 'OFFER';if(g.indexOf('dine')>=0)return 'DINE_IN';if(g.indexOf('delivery')>=0)return 'DELIVERY';if(g.indexOf('engagement')>=0)return 'ENGAGEMENT';if(g.indexOf('seasonal')>=0)return 'SEASONAL';if(product)return 'PRODUCT_PUSH';return 'BRAND_BUILDING';}
  function selectedVibes(){return Array.from(document.querySelectorAll('#vibeChecks input:checked')).map(function(el){return el.value;});}
  function readBrief(){var fmt=formatPreset($('formatPreset').value);var product=$('productId').value.trim();return {schemaVersion:1,id:'brief-'+Date.now(),clientId:'T001',brandId:$('brandId').value,goal:$('goal').value,description:$('description').value.trim()||$('goal').value+(product?' for '+product:''),product:product?{id:product,name:product}:undefined,branchId:$('branchId').value||undefined,salesChannel:$('salesChannel').value||undefined,audience:$('audience').value.split(',').map(function(v){return v.trim();}).filter(Boolean),vibe:selectedVibes().length?selectedVibes():['premium'],format:{preset:fmt.preset,width:fmt.width,height:fmt.height},contentRequirements:{showPrice:$('showPrice').checked,showOffer:$('goal').value.toLowerCase().indexOf('offer')>=0,showCTA:$('showCta').checked,showProductName:$('showProduct').checked,showBranch:$('showBranch').checked,showContactDetails:false,showCampaignDates:false},brandKitId:'ATTHAS_WORKING_V1',createdAt:new Date().toISOString()};}
  function intentFromBrief(brief){var fmt=formatPreset(brief.format.preset);var product=brief.product&&brief.product.id?brief.product.id:'';var raw=[brief.goal,brief.description,product?('featuring '+product):'',brief.branchId||'',brief.vibe.join(' '),brief.contentRequirements.showPrice?'show price':'no price',fmt.channel,fmt.assetType].filter(Boolean).join('. ');return {rawRequest:raw,brandId:brief.brandId,branchScope:brief.branchId||'BRAND_WIDE',campaignType:campaignType(brief.goal,product),objective:brief.description,audience:brief.audience.join(', '),channel:fmt.channel,assetType:fmt.assetType,productId:product||undefined,salesChannel:brief.salesChannel||undefined,showPrice:brief.contentRequirements.showPrice,mode:$('productionMode').value,assumptions:[],missingFields:[]};}
  function showProgress(active){var names=['Understanding your brief','Confirming business truth','Building campaign message','Planning composition','Creating imagery','Assembling editable design'];var box=$('generationProgress');box.classList.remove('hidden');box.innerHTML=names.map(function(name,i){var cls=i<active?'done':i===active?'active':'';return '<div class="progress-item '+cls+'"><span class="dot"></span>'+esc(name)+'</div>';}).join('');}
  function renderTruth(questionnaire){$('truthQuestions').innerHTML=questionnaire.questions.map(function(q,i){var value=q.storedValue!==undefined?q.storedValue:q.suggestedValue!==undefined?q.suggestedValue:'';if(Array.isArray(value))value=value.join(', ');else if(value&&typeof value==='object')value=JSON.stringify(value);return '<div class="truth-card"><p>'+esc(q.prompt)+'</p><input data-truth-index="'+i+'" value="'+esc(value)+'" style="width:100%;border:1px solid var(--line);background:#111315;color:var(--text);border-radius:8px;padding:9px" /></div>';}).join('');$('truthModal').classList.remove('hidden');}
  async function prepareCreative(){try{state.brief=readBrief();if(!state.brief.description||!state.brief.audience.length)throw new Error('Campaign description and audience are required.');showProgress(0);setStatus('Preparing governed campaign…');var intent=intentFromBrief(state.brief);var prepared=await api('/api/ui/prepare',{method:'POST',body:JSON.stringify({request:intent.rawRequest,intent:intent})});state.prepared=prepared;showProgress(1);renderTruth(prepared.questionnaire);setStatus('Publishing facts require confirmation.');}catch(error){setStatus(error.message,'error');}}
  function truthAnswers(){return state.prepared.questionnaire.questions.map(function(q,i){var input=document.querySelector('[data-truth-index="'+i+'"]');var current=input.value;var stored=q.storedValue;if(Array.isArray(stored))stored=stored.join(', ');else if(stored&&typeof stored==='object')stored=JSON.stringify(stored);else if(stored!==undefined)stored=String(stored);if(q.kind==='CONFIRM_STORED'&&current===stored)return {label:q.label,action:'CONFIRM',updateStoredTruth:false};return {label:q.label,action:q.kind==='CONFIRM_STORED'?'REPLACE':'PROVIDE',value:current,updateStoredTruth:false};});}
  function fileDataUrl(file){return new Promise(function(resolve,reject){var reader=new FileReader();reader.onload=function(){resolve(String(reader.result));};reader.onerror=reject;reader.readAsDataURL(file);});}
  async function uploadBaseImage(intent){var file=$('baseImage').files&&$('baseImage').files[0];if(!file)return undefined;var dataUrl=await fileDataUrl(file);var asset=await api('/api/ui/upload',{method:'POST',body:JSON.stringify({sessionId:state.prepared.sessionId,campaignId:state.prepared.campaignId,brandId:intent.brandId,branchId:intent.branchScope!=='BRAND_WIDE'?intent.branchScope:undefined,productId:intent.productId,filename:file.name,dataUrl:dataUrl,approvedForAds:$('approvedAds').checked,appearanceVerified:$('appearanceVerified').checked,ingredientMatchVerified:$('ingredientVerified').checked})});return asset.assetId;}
  async function confirmAndGenerate(){try{$('confirmTruth').disabled=true;var intent=state.prepared.intent||intentFromBrief(state.brief);var confirmed=await api('/api/ui/confirm',{method:'POST',body:JSON.stringify({campaignId:state.prepared.campaignId,sessionId:state.prepared.sessionId,intent:intent,answers:truthAnswers(),confirmedBy:'creative-studio-user'})});state.snapshot=confirmed.snapshot;state.brief.truthSnapshotId='task:'+state.snapshot.sessionId;$('truthModal').classList.add('hidden');showProgress(2);setStatus('Generating governed campaign…');var baseImageAssetId=await uploadBaseImage(intent);showProgress(4);var result=await api('/api/ui/produce',{method:'POST',body:JSON.stringify({campaignId:state.prepared.campaignId,sessionId:state.prepared.sessionId,intent:intent,taskTruthSnapshot:state.snapshot,mode:$('productionMode').value,baseImageAssetId:baseImageAssetId})});if(result.status!=='TASK_CONFIRMED_AND_PRODUCED')throw new Error('Production did not reach the governed production stage: '+result.status);var p=result.production;if(p.status!=='DRAFT_RENDERED'&&p.status!=='FINAL_RENDERED')throw new Error('Production stopped at '+p.status+'. Resolve its governance/QA issue before opening the editor.');showProgress(5);var project=await api('/api/studio/open',{method:'POST',body:JSON.stringify({campaignId:state.prepared.campaignId,brief:state.brief})});loadProject(project);showProgress(6);setStatus('Editable layered design assembled.','ok');}catch(error){setStatus(error.message,'error');}finally{$('confirmTruth').disabled=false;}}
  async function openCampaign(){var campaignId=$('campaignSelect').value;if(!campaignId){setStatus('Choose a campaign first.','error');return;}try{setStatus('Opening campaign as layered design…');var project=await api('/api/studio/open',{method:'POST',body:JSON.stringify({campaignId:campaignId})});loadProject(project);setStatus('Campaign opened in Creative Studio.','ok');}catch(error){setStatus(error.message,'error');}}
  function loadProject(project){state.project=project;state.selectedLayerId=project.document.layers.find(function(l){return l.type==='headline';})?.id||project.document.layers[0]?.id||null;$('emptyCanvas').classList.add('hidden');$('artboardWrap').classList.remove('hidden');$('qaBtn').disabled=false;$('exportBtn').disabled=false;renderAll();}
  function currentDoc(){return state.project&&state.project.document;}
  function selectedLayer(){var doc=currentDoc();return doc?doc.layers.find(function(l){return l.id===state.selectedLayerId;}):null;}
  function assetUrl(layer){return layer.asset&&layer.asset.uri?layer.asset.uri:'';}
  function layerSvg(layer){var rotate='rotate('+layer.rotation+' '+(layer.x+layer.width/2)+' '+(layer.y+layer.height/2)+')';var common=' opacity="'+layer.opacity+'" transform="'+rotate+'" data-layer-id="'+esc(layer.id)+'"';if(!layer.visible)return '';if(layer.type==='background'||layer.type==='image'||layer.type==='logo'){var href=assetUrl(layer);if(!href&&layer.type==='background')return '<rect x="'+layer.x+'" y="'+layer.y+'" width="'+layer.width+'" height="'+layer.height+'" fill="'+esc(layer.fill||'#000')+'"'+common+'></rect>';return '<image x="'+layer.x+'" y="'+layer.y+'" width="'+layer.width+'" height="'+layer.height+'" href="'+esc(href)+'" preserveAspectRatio="'+(layer.fit==='contain'||layer.type==='logo'?'xMidYMid meet':'xMidYMid slice')+'"'+common+'></image>';}
    if(layer.type==='shape'){if(layer.shape==='ellipse')return '<ellipse cx="'+(layer.x+layer.width/2)+'" cy="'+(layer.y+layer.height/2)+'" rx="'+(layer.width/2)+'" ry="'+(layer.height/2)+'" fill="'+esc(layer.fill||'transparent')+'" stroke="'+esc(layer.stroke||'none')+'" stroke-width="'+(layer.strokeWidth||0)+'"'+common+'></ellipse>';if(layer.shape==='line')return '<line x1="'+layer.x+'" y1="'+layer.y+'" x2="'+(layer.x+layer.width)+'" y2="'+(layer.y+layer.height)+'" stroke="'+esc(layer.stroke||layer.fill||'#000')+'" stroke-width="'+(layer.strokeWidth||1)+'"'+common+'></line>';return '<rect x="'+layer.x+'" y="'+layer.y+'" width="'+layer.width+'" height="'+layer.height+'" rx="'+(layer.cornerRadius||0)+'" fill="'+esc(layer.fill||'transparent')+'" stroke="'+esc(layer.stroke||'none')+'" stroke-width="'+(layer.strokeWidth||0)+'"'+common+'></rect>';}
    if(layer.type==='text'){var justify=layer.align==='center'?'center':layer.align==='right'?'flex-end':'flex-start';var align=(layer.role==='cta'||layer.role==='price')?'center':'flex-start';return '<foreignObject x="'+layer.x+'" y="'+layer.y+'" width="'+layer.width+'" height="'+layer.height+'"'+common+'><div xmlns="http://www.w3.org/1999/xhtml" style="width:100%;height:100%;overflow:hidden;display:flex;align-items:'+align+';justify-content:'+justify+';white-space:pre-wrap;text-align:'+layer.align+';font-family:'+esc(layer.fontFamily)+',Arial,sans-serif;font-size:'+layer.fontSize+'px;font-weight:'+layer.fontWeight+';line-height:'+layer.lineHeight+';letter-spacing:'+layer.letterSpacing+'px;color:'+esc(layer.fill)+';pointer-events:none">'+esc(layer.text)+'</div></foreignObject>';}
    return '';}
  function renderCanvas(){var doc=currentDoc();if(!doc)return;var svg=$('artboard');svg.setAttribute('viewBox','0 0 '+doc.artboard.width+' '+doc.artboard.height);svg.setAttribute('width',doc.artboard.width);svg.setAttribute('height',doc.artboard.height);svg.style.background=doc.artboard.background;var sorted=doc.layers.slice().sort(function(a,b){return a.zIndex-b.zIndex;});var html=sorted.map(layerSvg).join('');if(state.guides){var sx=doc.artboard.width*.05,sy=doc.artboard.height*.05,sw=doc.artboard.width*.9,sh=doc.artboard.height*.9;html+='<g pointer-events="none"><rect x="'+sx+'" y="'+sy+'" width="'+sw+'" height="'+sh+'" fill="none" stroke="#47a3ff" stroke-width="1" stroke-dasharray="8 8" opacity=".55"></rect><line x1="'+(doc.artboard.width/2)+'" y1="0" x2="'+(doc.artboard.width/2)+'" y2="'+doc.artboard.height+'" stroke="#47a3ff" stroke-width="1" opacity=".25"></line><line x1="0" y1="'+(doc.artboard.height/2)+'" x2="'+doc.artboard.width+'" y2="'+(doc.artboard.height/2)+'" stroke="#47a3ff" stroke-width="1" opacity=".25"></line></g>';}
    var sel=selectedLayer();if(sel&&sel.visible)html+='<rect x="'+sel.x+'" y="'+sel.y+'" width="'+sel.width+'" height="'+sel.height+'" fill="none" stroke="#ffd21a" stroke-width="3" stroke-dasharray="9 5" pointer-events="none" transform="rotate('+sel.rotation+' '+(sel.x+sel.width/2)+' '+(sel.y+sel.height/2)+')"></rect>';svg.innerHTML=html;}
  function renderLayers(){var doc=currentDoc();$('layersList').innerHTML=doc?doc.layers.slice().sort(function(a,b){return b.zIndex-a.zIndex;}).map(function(l){return '<div class="layer-row '+(l.id===state.selectedLayerId?'selected':'')+'" data-select-layer="'+esc(l.id)+'"><button class="iconbtn" data-eye="'+esc(l.id)+'">'+(l.visible?'●':'○')+'</button><div class="layer-name"><strong>'+esc(l.name)+'</strong><small>'+esc(l.type)+' · z '+l.zIndex+(l.aiEditable?' · AI':'')+'</small></div><button class="iconbtn" data-up="'+esc(l.id)+'">↑</button><button class="iconbtn" data-lock="'+esc(l.id)+'">'+(l.locked?'🔒':'◇')+'</button></div>';}).join(''):'<p class="note">No design loaded.</p>';}
  function renderAssets(){var doc=currentDoc();if(!doc){$('assetsList').innerHTML='<p class="note">No assets loaded.</p>';return;}$('assetsList').innerHTML=doc.layers.map(function(l){var a=l.asset;if(!a)return '';return '<div class="asset-card"><strong>'+esc(l.name)+'</strong><small>'+esc(a.source)+(a.visualTruthClass?' · '+esc(a.visualTruthClass):'')+'<br>'+esc(a.assetId)+'</small></div>';}).join('')||'<p class="note">No asset-backed layers.</p>';}
  function propertyField(id,label,value,type){return '<div class="field"><label>'+label+'</label><input id="'+id+'" type="'+(type||'number')+'" value="'+esc(value)+'" /></div>';}
  function renderProperties(){var layer=selectedLayer();if(!layer){$('properties').classList.add('hidden');$('propertiesEmpty').classList.remove('hidden');$('aiApplyBtn').disabled=true;return;}$('propertiesEmpty').classList.add('hidden');$('properties').classList.remove('hidden');$('aiApplyBtn').disabled=!layer.aiEditable;var html='<div class="section"><h3>'+esc(layer.name)+'</h3><div class="prop-grid">'+propertyField('propX','X',layer.x)+propertyField('propY','Y',layer.y)+propertyField('propW','Width',layer.width)+propertyField('propH','Height',layer.height)+propertyField('propRotation','Rotation',layer.rotation)+propertyField('propOpacity','Opacity',layer.opacity)+'</div><div class="toolbar-row"><button id="applyMove" class="secondary">Move</button><button id="applySize" class="secondary">Resize</button></div><div class="toolbar-row"><button id="applyRotation" class="secondary">Rotate</button><button id="applyOpacity" class="secondary">Opacity</button></div></div>';
    if(layer.type==='text')html+='<div class="section"><h3>Typography</h3><div class="field"><label>Text</label><textarea id="propText">'+esc(layer.text)+'</textarea></div><div class="prop-grid">'+propertyField('propFont','Font',layer.fontFamily,'text')+propertyField('propFontSize','Size',layer.fontSize)+propertyField('propWeight','Weight',layer.fontWeight)+propertyField('propLineHeight','Line height',layer.lineHeight)+propertyField('propLetterSpacing','Letter spacing',layer.letterSpacing)+propertyField('propFill','Color',layer.fill,'text')+'</div><div class="field"><label>Alignment</label><select id="propAlign"><option '+(layer.align==='left'?'selected':'')+'>left</option><option '+(layer.align==='center'?'selected':'')+'>center</option><option '+(layer.align==='right'?'selected':'')+'>right</option></select></div><button id="applyText" class="secondary" style="width:100%">Apply Text & Typography</button></div>';
    html+='<div class="section"><h3>Layer controls</h3><div class="toolbar-row"><button id="duplicateLayer" class="secondary" '+(layer.type==='logo'?'disabled':'')+'>Duplicate</button><button id="deleteLayer" class="secondary danger" '+((layer.type==='logo'||layer.type==='background')?'disabled':'')+'>Delete</button></div></div>';$('properties').innerHTML=html;bindPropertyButtons();}
  function renderQa(){var qa=state.project&&state.project.qa;var badge=$('qaBadge');if(!qa){badge.className='pill';badge.textContent='QA not run';$('qaSummary').textContent='Run Final QA to validate truth, brand and layout.';$('qaList').innerHTML='';return;}badge.className='pill '+(qa.decision==='PASS'?'ok':qa.decision==='WARN'?'warn':'block');badge.textContent='QA '+qa.decision;$('qaSummary').textContent=qa.issues.length?qa.issues.length+' issue(s)':'No deterministic issues found.';$('qaList').innerHTML=(qa.issues||[]).map(function(i){return '<div class="qa-item '+esc(i.severity||'LOW')+'"><strong>'+esc(i.code||'Issue')+'</strong><br>'+esc(i.message||String(i))+'</div>';}).join('');}
  function renderMeta(){var doc=currentDoc();if(!doc){$('designMeta').textContent='No design loaded';$('undoBtn').disabled=true;$('redoBtn').disabled=true;return;}$('designMeta').textContent=doc.id+' · v'+doc.version+' · '+doc.artboard.width+'×'+doc.artboard.height;$('undoBtn').disabled=state.project.state.currentVersion<=1;$('redoBtn').disabled=state.project.state.currentVersion>=state.project.state.maxVersion;}
  function renderAll(){renderCanvas();renderLayers();renderAssets();renderProperties();renderQa();renderMeta();}
  async function operation(op){try{var result=await api('/api/studio/operation',{method:'POST',body:JSON.stringify({designId:currentDoc().id,operation:op})});state.project=result;renderAll();setStatus('Design updated locally.','ok');return result;}catch(error){setStatus(error.message,'error');throw error;}}
  function bindPropertyButtons(){var layer=selectedLayer();if(!layer)return;$('applyMove').onclick=function(){operation({type:'MOVE_LAYER',layerId:layer.id,x:Number($('propX').value),y:Number($('propY').value)});};$('applySize').onclick=function(){operation({type:'RESIZE_LAYER',layerId:layer.id,width:Number($('propW').value),height:Number($('propH').value)});};$('applyRotation').onclick=function(){operation({type:'ROTATE_LAYER',layerId:layer.id,rotation:Number($('propRotation').value)});};$('applyOpacity').onclick=function(){operation({type:'SET_OPACITY',layerId:layer.id,opacity:Number($('propOpacity').value)});};if(layer.type==='text')$('applyText').onclick=async function(){var next=$('propText').value;if(next!==layer.text)await operation({type:'UPDATE_TEXT',layerId:layer.id,text:next});var refreshed=selectedLayer();await operation({type:'UPDATE_TEXT_STYLE',layerId:refreshed.id,patch:{fontFamily:$('propFont').value,fontSize:Number($('propFontSize').value),fontWeight:Number($('propWeight').value),lineHeight:Number($('propLineHeight').value),letterSpacing:Number($('propLetterSpacing').value),align:$('propAlign').value,fill:$('propFill').value}});};$('duplicateLayer').onclick=function(){operation({type:'DUPLICATE_LAYER',layerId:layer.id,newLayerId:layer.id+'-copy-'+Date.now()});};$('deleteLayer').onclick=function(){operation({type:'DELETE_LAYER',layerId:layer.id}).then(function(){state.selectedLayerId=currentDoc().layers[0]?.id||null;renderAll();});};}
  function svgPoint(event){var svg=$('artboard');var pt=svg.createSVGPoint();pt.x=event.clientX;pt.y=event.clientY;return pt.matrixTransform(svg.getScreenCTM().inverse());}
  function snapped(layer,x,y){var doc=currentDoc(),threshold=12;var safeX=doc.artboard.width*.05,safeY=doc.artboard.height*.05;var centerX=x+layer.width/2,centerY=y+layer.height/2;if(Math.abs(centerX-doc.artboard.width/2)<threshold)x=doc.artboard.width/2-layer.width/2;if(Math.abs(centerY-doc.artboard.height/2)<threshold)y=doc.artboard.height/2-layer.height/2;if(Math.abs(x-safeX)<threshold)x=safeX;if(Math.abs(y-safeY)<threshold)y=safeY;return {x:x,y:y};}
  function setupCanvasEvents(){var svg=$('artboard');svg.addEventListener('pointerdown',function(event){var node=event.target.closest&&event.target.closest('[data-layer-id]');if(!node)return;var id=node.getAttribute('data-layer-id');var layer=currentDoc().layers.find(function(l){return l.id===id;});state.selectedLayerId=id;renderLayers();renderProperties();renderCanvas();if(!layer||layer.locked)return;var point=svgPoint(event);state.drag={layerId:id,startX:point.x,startY:point.y,originX:layer.x,originY:layer.y};svg.setPointerCapture(event.pointerId);});svg.addEventListener('pointermove',function(event){if(!state.drag)return;var layer=currentDoc().layers.find(function(l){return l.id===state.drag.layerId;});if(!layer)return;var point=svgPoint(event);var pos=snapped(layer,state.drag.originX+(point.x-state.drag.startX),state.drag.originY+(point.y-state.drag.startY));layer.x=Math.round(pos.x);layer.y=Math.round(pos.y);renderCanvas();});svg.addEventListener('pointerup',function(event){if(!state.drag)return;var drag=state.drag;state.drag=null;var layer=currentDoc().layers.find(function(l){return l.id===drag.layerId;});if(layer)operation({type:'MOVE_LAYER',layerId:layer.id,x:layer.x,y:layer.y});try{svg.releasePointerCapture(event.pointerId);}catch(_e){}});}
  async function undoRedo(action){try{var result=await api('/api/studio/'+action,{method:'POST',body:JSON.stringify({designId:currentDoc().id})});state.project=result;renderAll();setStatus(action==='undo'?'Undid last edit.':'Redid edit.','ok');}catch(error){setStatus(error.message,'error');}}
  async function runQa(){try{setStatus('Running deterministic final QA…');var qa=await api('/api/studio/qa',{method:'POST',body:JSON.stringify({designId:currentDoc().id})});state.project.qa=qa;renderQa();setStatus('QA '+qa.decision+'.',qa.decision==='BLOCK'?'error':'ok');}catch(error){setStatus(error.message,'error');}}
  async function exportDesign(){try{setStatus('Rendering '+$('exportPreset').value+' PNG…');var out=await api('/api/studio/export',{method:'POST',body:JSON.stringify({designId:currentDoc().id,preset:$('exportPreset').value})});window.open(out.outputPath,'_blank','noopener');setStatus('Export rendered from DesignDocument.','ok');}catch(error){setStatus(error.message,'error');}}
  async function aiEdit(){var layer=selectedLayer();if(!layer)return;var instruction=$('aiInstruction').value.trim();if(!instruction){setStatus('Enter an AI edit instruction.','error');return;}try{setStatus('Applying AI edit to '+layer.name+' only…');var endpoint=layer.type==='text'?'/api/studio/ai/text':(layer.type==='image'||layer.type==='background')?'/api/studio/ai/image':null;if(!endpoint)throw new Error('This layer type has no AI action.');var result=await api(endpoint,{method:'POST',body:JSON.stringify({designId:currentDoc().id,layerId:layer.id,instruction:instruction})});state.project=result;renderAll();setStatus('AI edit applied to selected layer only.','ok');}catch(error){setStatus(error.message,'error');}}
  function populateBranches(){var brand=$('brandId').value;var branches=(state.uiBootstrap&&state.uiBootstrap.branches||[]).filter(function(b){return b.brandId===brand;});$('branchId').innerHTML='<option value="">Brand-wide</option>'+branches.map(function(b){return '<option value="'+esc(b.branchId)+'">'+esc(b.name)+'</option>';}).join('');}
  function populateCampaigns(){var campaigns=state.bootstrap&&state.bootstrap.campaigns||[];$('campaignSelect').innerHTML='<option value="">Choose a completed campaign…</option>'+campaigns.map(function(c){return '<option value="'+esc(c.campaignId)+'">'+esc(c.campaignId)+' · '+esc(c.state||'campaign')+'</option>';}).join('');}
  function setupTabs(){document.querySelectorAll('.tab').forEach(function(btn){btn.addEventListener('click',function(){document.querySelectorAll('.tab').forEach(function(b){b.classList.remove('active');});document.querySelectorAll('.tabpanel').forEach(function(p){p.classList.add('hidden');});btn.classList.add('active');$('tab-'+btn.dataset.tab).classList.remove('hidden');});});}
  function setupLayerButtons(){$('layersList').addEventListener('click',function(event){var eye=event.target.closest('[data-eye]'),up=event.target.closest('[data-up]'),lock=event.target.closest('[data-lock]');if(eye){event.stopPropagation();var l=currentDoc().layers.find(function(x){return x.id===eye.dataset.eye;});operation({type:'SET_VISIBILITY',layerId:l.id,visible:!l.visible});return;}if(up){event.stopPropagation();var u=currentDoc().layers.find(function(x){return x.id===up.dataset.up;});operation({type:'REORDER_LAYER',layerId:u.id,zIndex:u.zIndex+1});return;}if(lock){event.stopPropagation();var k=currentDoc().layers.find(function(x){return x.id===lock.dataset.lock;});operation({type:'SET_LOCK',layerId:k.id,locked:!k.locked});return;}var row=event.target.closest('[data-select-layer]');if(row){state.selectedLayerId=row.dataset.selectLayer;renderAll();}});}
  async function init(){setupTabs();setupCanvasEvents();setupLayerButtons();var vibes=['energetic','premium','bold','playful','minimal','warm','authentic','youthful','cinematic','street-food energy'];$('vibeChecks').innerHTML=vibes.map(function(v,i){return '<label class="chip"><input type="checkbox" value="'+esc(v)+'" '+((i===0||i===1)?'checked':'')+' /> '+esc(v)+'</label>';}).join('');$('prepareBtn').onclick=prepareCreative;$('confirmTruth').onclick=confirmAndGenerate;$('cancelTruth').onclick=function(){$('truthModal').classList.add('hidden');};$('openCampaignBtn').onclick=openCampaign;$('brandId').onchange=populateBranches;$('undoBtn').onclick=function(){undoRedo('undo');};$('redoBtn').onclick=function(){undoRedo('redo');};$('guidesBtn').onclick=function(){state.guides=!state.guides;$('guidesBtn').textContent='Guides: '+(state.guides?'On':'Off');renderCanvas();};$('qaBtn').onclick=runQa;$('exportBtn').onclick=exportDesign;$('aiApplyBtn').onclick=aiEdit;document.querySelectorAll('.aiPreset').forEach(function(btn){btn.onclick=function(){$('aiInstruction').value=btn.dataset.instruction;aiEdit();};});try{var results=await Promise.all([api('/api/studio/bootstrap'),api('/api/ui/bootstrap')]);state.bootstrap=results[0];state.uiBootstrap=results[1];populateBranches();populateCampaigns();setStatus('Creative Studio ready.','ok');}catch(error){setStatus(error.message,'error');}}
  init();
})();
</script>
</body>
</html>`;
}
