import { creativeStudioComponentsHtml } from "./creativeStudioComponentsHtml.js";

function injectBefore(html: string, marker: string, content: string): string {
  if (!html.includes(marker)) throw new Error(`CREATIVE_STUDIO_COMPONENT_AUTHORING_MARKER_MISSING: ${marker}`);
  return html.replace(marker, `${content}${marker}`);
}

export function creativeStudioComponentAuthoringHtml(): string {
  let html = creativeStudioComponentsHtml();

  const style = `<style>
    #componentAuthoring textarea{width:100%;min-height:72px;resize:vertical;border:1px solid var(--line);background:#111315;color:var(--text);border-radius:8px;padding:8px;font:inherit}
    #componentAuthoring .authoring-diff{white-space:pre-wrap;background:#0d1012;border:1px solid var(--line);border-radius:8px;padding:8px;min-height:46px;font-size:10px;color:var(--muted);line-height:1.45}
    #componentAuthoring .authoring-diff.review{border-color:#806b21;color:#ead987}
    #componentAuthoring .authoring-diff.blocked{border-color:#7e2b2b;color:#ff9d9d}
    #componentAuthoring button:disabled{opacity:.38;cursor:not-allowed}
    #componentAuthoring .version-audit{font-size:10px;color:var(--muted);line-height:1.45;max-height:110px;overflow:auto;margin-top:7px}
  </style>`;
  html = injectBefore(html, "</head>", style);

  const script = `<script>
(function(){
  'use strict';
  var pending=null,lastFamilyId=null;
  function $(id){return document.getElementById(id);}
  function project(){return window.__creativeStudioCurrentProject&&window.__creativeStudioCurrentProject();}
  function primary(){return window.__creativeStudioSelectedLayer&&window.__creativeStudioSelectedLayer();}
  function selection(){var ids=window.__creativeStudioMultiSelectionIds?window.__creativeStudioMultiSelectionIds():[];if(ids.length)return ids;var layer=primary();return layer?[layer.id]:[];}
  function doc(){var p=project();return p&&p.document;}
  function byId(id){var d=doc();return d&&d.layers.find(function(layer){return layer.id===id;});}
  function selectedGroup(){var layers=selection().map(byId).filter(Boolean);return layers.length===1&&layers[0].type==='group'?layers[0]:null;}
  function status(message,type){if(window.__creativeStudioSetStatus)window.__creativeStudioSetStatus(message,type);}
  async function api(path,options){var response=await fetch(path,Object.assign({headers:{'content-type':'application/json'}},options||{}));var data=await response.json();if(!response.ok)throw new Error(data.error||('HTTP '+response.status));return data;}
  function selectedFamilyId(){var select=$('componentFamilySelect');return select&&select.value?select.value:'';}
  function invalidate(reason){pending=null;var publish=$('publishComponentVersionBtn');if(publish)publish.disabled=true;var diff=$('componentVersionDiff');if(diff&&reason)diff.textContent=reason;}
  function renderDiff(preview){var lines=[];lines.push('Compatibility: '+preview.compatibility);lines.push('v'+preview.baseVersion+' → v'+preview.proposedVersion);lines.push('Templates: '+preview.diff.templateCount.before+' → '+preview.diff.templateCount.after);if(preview.diff.textRoles.added.length)lines.push('Text roles added: '+preview.diff.textRoles.added.join(', '));if(preview.diff.textRoles.removed.length)lines.push('Text roles removed: '+preview.diff.textRoles.removed.join(', '));if(preview.diff.textRoles.styleOrGeometryChanged.length)lines.push('Text style/geometry changed: '+preview.diff.textRoles.styleOrGeometryChanged.join(', '));if(preview.diff.shapes.before!==preview.diff.shapes.after)lines.push('Shapes: '+preview.diff.shapes.before+' → '+preview.diff.shapes.after);else if(preview.diff.shapes.styleOrGeometryChanged)lines.push('Shape style/geometry changed.');if(preview.diff.truthDependencies.added.length)lines.push('Truth dependencies added: '+preview.diff.truthDependencies.added.join(', '));if(preview.diff.truthDependencies.removed.length)lines.push('Truth dependencies removed: '+preview.diff.truthDependencies.removed.join(', '));if(preview.issues.length)lines.push('Review: '+preview.issues.join(' '));if(lines.length===3)lines.push('No semantic structure change detected; geometry/style-only authoring is compatible.');var target=$('componentVersionDiff');target.textContent=lines.join('\n');target.className='authoring-diff '+(preview.compatibility==='BLOCKED'?'blocked':preview.compatibility==='REVIEW_REQUIRED'?'review':'');}
  async function preview(){var d=doc(),group=selectedGroup(),familyId=selectedFamilyId();if(!d||!group||!familyId){status('Select one group and one component family before previewing.','error');return;}try{status('Comparing edited group against latest component version…');var result=await api('/api/studio/components/version-preview',{method:'POST',body:JSON.stringify({designId:d.id,groupLayerId:group.id,familyId:familyId})});pending={preview:result.preview,designVersion:d.version,groupLayerId:group.id,familyId:familyId};renderDiff(result.preview);$('publishComponentVersionBtn').disabled=result.preview.compatibility==='BLOCKED';status(result.preview.compatibility==='COMPATIBLE'?'Component version is compatible for publish.':result.preview.compatibility==='REVIEW_REQUIRED'?'Component version requires explicit compatibility review.':'Component version is blocked.','ok');}catch(error){invalidate();status(error.message,'error');}}
  async function publish(){var d=doc(),group=selectedGroup();if(!d||!group||!pending){status('Preview the current edited group before publishing.','error');return;}if(d.version!==pending.designVersion||group.id!==pending.groupLayerId||selectedFamilyId()!==pending.familyId){invalidate('Preview is stale. Run Preview Version Changes again.');status('Component preview is stale.','error');return;}var notes=$('componentVersionNotes').value.trim();if(notes.length<5){status('Version notes must contain at least 5 characters.','error');return;}var accept=false;if(pending.preview.compatibility==='REVIEW_REQUIRED'){accept=window.confirm('This version changes component roles, layer count, or truth dependencies. Publish after explicit compatibility review?');if(!accept)return;}try{status('Publishing immutable component version…');var result=await api('/api/studio/components/publish-version',{method:'POST',body:JSON.stringify({designId:d.id,groupLayerId:group.id,familyId:pending.familyId,expectedBaseComponentId:pending.preview.baseComponentId,expectedPreviewToken:pending.preview.previewToken,versionNotes:notes,acceptReviewRequired:accept})});$('componentVersionNotes').value='';invalidate('Published '+result.component.id+'. Existing instances were not changed.');var refresh=$('refreshComponentsBtn');if(refresh)refresh.click();setTimeout(loadAudit,150);status('Published immutable component v'+result.record.version+'. Existing design instances remain unchanged.','ok');}catch(error){status(error.message,'error');}}
  async function loadAudit(){var d=doc(),familyId=selectedFamilyId(),target=$('componentVersionAudit');if(!target)return;if(!d||!familyId){target.textContent='Select a family to view authored version notes.';return;}lastFamilyId=familyId;try{var result=await api('/api/studio/components/version-audit?designId='+encodeURIComponent(d.id)+'&familyId='+encodeURIComponent(familyId));if(lastFamilyId!==familyId)return;var records=result.records||[];target.textContent=records.length?records.slice().reverse().map(function(record){return 'v'+record.version+' · '+record.compatibility+' · '+record.versionNotes;}).join('\n'):'No authored version notes yet. Legacy/duplicated versions remain immutable but may predate authoring notes.';}catch(error){target.textContent=error.message;}}
  function update(){var group=selectedGroup(),familyId=selectedFamilyId();var previewBtn=$('previewComponentVersionBtn');if(previewBtn)previewBtn.disabled=!(group&&familyId);if(pending){var d=doc();if(!d||d.version!==pending.designVersion||!group||group.id!==pending.groupLayerId||familyId!==pending.familyId)invalidate('Selection or document changed. Preview again before publishing.');}}
  function inject(){var library=$('componentLibrary');if(!library||$('componentAuthoring'))return;var block=document.createElement('div');block.id='componentAuthoring';block.style.marginTop='14px';block.innerHTML='<h3>Author New Version</h3><div class="note">Edit a group, compare it with the selected family latest version, then publish an immutable next version. Previous versions and existing instances never auto-update.</div><button id="previewComponentVersionBtn" class="secondary" style="width:100%;margin-top:8px" disabled>Preview Version Changes</button><pre id="componentVersionDiff" class="authoring-diff" style="margin-top:7px">Select a family and one group, then preview structural and truth-dependency changes.</pre><textarea id="componentVersionNotes" maxlength="500" placeholder="Required version notes: what changed and why"></textarea><button id="publishComponentVersionBtn" class="secondary" style="width:100%;margin-top:7px" disabled>Publish as Next Immutable Version</button><div id="componentVersionAudit" class="version-audit">Select a family to view authored version notes.</div>';library.appendChild(block);$('previewComponentVersionBtn').addEventListener('click',preview);$('publishComponentVersionBtn').addEventListener('click',publish);var family=$('componentFamilySelect');if(family)family.addEventListener('change',function(){invalidate('Family changed. Preview again before publishing.');loadAudit();update();});}
  function bind(){inject();document.addEventListener('click',function(){setTimeout(update,0);},true);var meta=$('designMeta');if(meta&&window.MutationObserver)new MutationObserver(function(){update();}).observe(meta,{childList:true,subtree:true});setTimeout(function(){update();loadAudit();},0);}
  bind();
})();
</script>`;
  html = injectBefore(html, "</body>", script);
  return html;
}
