import { creativeStudioComponentMigrationHtml } from "./creativeStudioComponentMigrationHtml.js";

function injectBefore(html: string, marker: string, content: string): string {
  if (!html.includes(marker)) throw new Error(`CREATIVE_STUDIO_MIGRATION_OPERATIONS_MARKER_MISSING: ${marker}`);
  return html.replace(marker, `${content}${marker}`);
}

export function creativeStudioComponentMigrationOperationsHtml(): string {
  let html = creativeStudioComponentMigrationHtml();

  const style = `<style>
    #migrationOperations .ops-summary{font-size:10px;color:var(--muted);line-height:1.5;margin:7px 0}
    #migrationOperations .ops-list{max-height:330px;overflow:auto;border:1px solid var(--line);border-radius:8px;background:#0d1012;margin-top:7px}
    #migrationOperations .ops-plan{padding:8px;border-bottom:1px solid var(--line)}
    #migrationOperations .ops-plan:last-child{border-bottom:0}
    #migrationOperations .ops-item{padding:6px 0;border-top:1px dashed var(--line);font-size:10px;line-height:1.45}
    #migrationOperations .ops-status{display:inline-block;padding:1px 5px;border:1px solid var(--line);border-radius:999px;font-size:9px;margin-left:4px}
    #migrationOperations .ops-warning{color:#efcf72}
    #migrationOperations .ops-error{color:#ff9d9d}
    #migrationOperations .ops-ok{color:#9ed7aa}
    #migrationOperations .ops-actions{display:flex;gap:5px;flex-wrap:wrap;margin-top:5px}
    #migrationOperations .ops-actions button{font-size:9px;padding:5px 7px}
    #migrationOperations .ops-detail{white-space:pre-wrap;background:#111315;border:1px solid var(--line);border-radius:8px;padding:8px;min-height:48px;margin-top:7px;font-size:10px;line-height:1.45;color:var(--muted)}
  </style>`;
  html = injectBefore(html, "</head>", style);

  const script = `<script>
(function(){
  'use strict';
  var pendingRecovery=null,lastHistory=null;
  function $(id){return document.getElementById(id);}
  function esc(value){return String(value==null?'':value).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c];});}
  function project(){return window.__creativeStudioCurrentProject&&window.__creativeStudioCurrentProject();}
  function doc(){var p=project();return p&&p.document;}
  function familyId(){var el=$('componentFamilySelect');return el&&el.value?el.value:'';}
  function status(message,type){if(window.__creativeStudioSetStatus)window.__creativeStudioSetStatus(message,type);}
  async function api(path,options){var response=await fetch(path,Object.assign({headers:{'content-type':'application/json'}},options||{}));var data=await response.json();if(!response.ok)throw new Error(data.error||('HTTP '+response.status));return data;}
  function cls(state){if(state==='RECORDED_EXECUTION')return 'ops-ok';if(state==='PERSISTED_WITHOUT_EXECUTION_AUDIT')return 'ops-warning';if(state==='PENDING'||state==='STALE_CHANGED')return '';return 'ops-error';}
  function recoveryEligible(state){return state==='RECORDED_EXECUTION'||state==='PERSISTED_WITHOUT_EXECUTION_AUDIT';}
  function render(history){lastHistory=history;pendingRecovery=null;var list=$('migrationOperationsList'),summary=$('migrationOperationsSummary'),detail=$('migrationOperationsDetail'),recover=$('restorePreMigrationBtn');if(recover)recover.disabled=true;if(detail)detail.textContent='Select Inspect Diff or Preview Recovery on a migrated design.';var plans=history.plans||[],recoveries=history.recoveries||[];var interrupted=0,recorded=0;plans.forEach(function(entry){interrupted+=entry.totals.persistedWithoutAudit||0;recorded+=entry.totals.recorded||0;});summary.innerHTML=plans.length+' plan(s) · '+recorded+' audited migrated item(s) · '+interrupted+' persisted-without-audit item(s) · '+recoveries.length+' recovery record(s)';var rows=[];plans.forEach(function(entry){var plan=entry.plan,t=entry.totals;var items=entry.items.map(function(item){var current=item.currentDesignVersion?(' · current v'+item.currentDesignVersion):'';var actions='<button class="secondary" data-inspect-plan="'+esc(plan.planId)+'" data-inspect-item="'+esc(item.itemId)+'">Inspect Diff</button>';if(recoveryEligible(item.status))actions+='<button class="secondary" data-recover-plan="'+esc(plan.planId)+'" data-recover-item="'+esc(item.itemId)+'">Preview Recovery</button>';return '<div class="ops-item '+cls(item.status)+'"><strong>'+esc(item.designId)+'</strong> v'+item.sourceDesignVersion+' → v'+item.targetDesignVersion+current+'<span class="ops-status">'+esc(item.status)+'</span><br>'+esc(item.reason)+'<div class="ops-actions">'+actions+'</div></div>';}).join('');rows.push('<div class="ops-plan"><strong>'+esc(plan.planId)+'</strong> · target component v'+plan.targetVersion+'<br><span class="ops-summary">'+t.recorded+' audited · '+t.persistedWithoutAudit+' interrupted/persisted · '+t.pending+' pending · '+t.staleChanged+' stale · '+t.missingOrInconsistent+' inconsistent</span>'+items+'</div>');});if(recoveries.length){rows.push('<div class="ops-plan"><strong>Recovery Audit</strong>'+recoveries.slice(0,20).map(function(record){return '<div class="ops-item ops-ok">'+esc(record.designId)+' · restored v'+record.restoredContentFromVersion+' content as new v'+record.recoveryVersion+' · QA '+esc(record.qaDecision)+'<br>'+esc(record.recoveryId)+'</div>';}).join('')+'</div>');}list.innerHTML=rows.length?rows.join(''):'<div class="ops-plan">No migration plans exist for the selected family/context.</div>';Array.from(list.querySelectorAll('[data-inspect-plan]')).forEach(function(button){button.addEventListener('click',function(){inspect(button.getAttribute('data-inspect-plan'),button.getAttribute('data-inspect-item'));});});Array.from(list.querySelectorAll('[data-recover-plan]')).forEach(function(button){button.addEventListener('click',function(){previewRecovery(button.getAttribute('data-recover-plan'),button.getAttribute('data-recover-item'));});});}
  function findItem(planId,itemId){if(!lastHistory)return null;var planState=(lastHistory.plans||[]).find(function(entry){return entry.plan.planId===planId;});if(!planState)return null;var item=planState.items.find(function(entry){return entry.itemId===itemId;});return item?{planState:planState,item:item}:null;}
  async function loadHistory(){var d=doc();if(!d)return;var fid=familyId(),query='/api/studio/components/migration-history?designId='+encodeURIComponent(d.id)+(fid?'&familyId='+encodeURIComponent(fid):'');try{status('Reconciling migration plans, executions and design versions…');var result=await api(query);render(result);status('Migration operational history reconciled.','ok');}catch(error){status(error.message,'error');}}
  async function inspect(planId,itemId){var found=findItem(planId,itemId),detail=$('migrationOperationsDetail');if(!found||!detail)return;try{var item=found.item;var result=await api('/api/studio/compare',{method:'POST',body:JSON.stringify({designId:item.designId,fromVersion:item.sourceDesignVersion,toVersion:item.targetDesignVersion})});var lines=['Migration diff · '+item.designId+' v'+item.sourceDesignVersion+' → v'+item.targetDesignVersion,'Status: '+item.status,'Artboard changed: '+result.artboardChanged,'Layout changed: '+result.layoutChanged];(result.layerChanges||[]).forEach(function(change){lines.push(change.kind.toUpperCase()+' '+change.layerId+': '+change.fields.join(', '));});if(!(result.layerChanges||[]).length)lines.push('No layer-property changes detected.');detail.textContent=lines.join(String.fromCharCode(10));}catch(error){detail.textContent=error.message;status(error.message,'error');}}
  async function previewRecovery(planId,itemId){var d=doc(),detail=$('migrationOperationsDetail'),recover=$('restorePreMigrationBtn');if(!d||!detail||!recover)return;try{status('Previewing governed pre-migration recovery…');var result=await api('/api/studio/components/migration-recovery-preview',{method:'POST',body:JSON.stringify({designId:d.id,planId:planId,itemId:itemId})});pendingRecovery=result.preview;var p=result.preview,lines=['Recovery preview · '+p.designId,'Current v'+p.currentDesignVersion+' → proposed recovery v'+p.proposedRecoveryVersion,'Restore content from pre-migration v'+p.restoreSourceVersion,'Operational status: '+p.operationalStatus,'Current exact version approved: '+p.currentVersionApproved,'Deterministic QA: '+p.qa.decision,'Layer changes in original migration: '+p.comparison.layerChanges.length];if(p.blockers.length)lines.push('BLOCKERS: '+p.blockers.join(' '));if(p.currentVersionApproved)lines.push('Recovery requires explicit acknowledgement because the current exact version is approved. The approved version remains immutable; recovery creates a new unapproved revision.');detail.textContent=lines.join(String.fromCharCode(10));recover.disabled=!p.restorable;status(p.restorable?'Recovery preview is valid. Restore will create a new DesignDocument revision.':'Recovery is blocked by current deterministic QA.',p.restorable?'ok':'error');}catch(error){pendingRecovery=null;recover.disabled=true;detail.textContent=error.message;status(error.message,'error');}}
  async function restore(){var d=doc();if(!d||!pendingRecovery)return;var ack=false;if(pendingRecovery.currentVersionApproved){ack=window.confirm('The current exact design version is approved. Recovery will NOT alter that approval or version; it will create a new unapproved revision using pre-migration content. Continue?');if(!ack)return;}else if(!window.confirm('Restore the pre-migration content as a new DesignDocument revision? Historical migration and current versions remain immutable.'))return;try{status('Restoring pre-migration content as a new governed revision…');var result=await api('/api/studio/components/migration-recover',{method:'POST',body:JSON.stringify({designId:d.id,planId:pendingRecovery.planId,itemId:pendingRecovery.itemId,expectedPreviewToken:pendingRecovery.previewToken,acknowledgeApprovedCurrent:ack})});if(result.designId===d.id){var refreshed=await api('/api/studio/project?designId='+encodeURIComponent(d.id));if(window.__creativeStudioLoadProject)window.__creativeStudioLoadProject(refreshed);}pendingRecovery=null;$('restorePreMigrationBtn').disabled=true;await loadHistory();status('Pre-migration content restored as new v'+result.designVersion+' with deterministic QA '+result.qa.decision+'.','ok');}catch(error){status(error.message,'error');}}
  function inject(){var migration=$('componentMigration');if(!migration||$('migrationOperations'))return;var block=document.createElement('div');block.id='migrationOperations';block.style.marginTop='14px';block.innerHTML='<h3>Migration History & Recovery</h3><div class="note">Reconciles immutable plans/execution audits against actual design versions. Detects interrupted file-backed batches where a design revision exists without its execution audit. Recovery never rewinds or deletes history; it restores pre-migration content as a new revision.</div><button id="refreshMigrationHistoryBtn" class="secondary" style="width:100%;margin-top:8px">Refresh Migration History</button><div id="migrationOperationsSummary" class="ops-summary">Refresh to reconcile migration history.</div><div id="migrationOperationsList" class="ops-list"></div><pre id="migrationOperationsDetail" class="ops-detail">Select Inspect Diff or Preview Recovery on a migrated design.</pre><button id="restorePreMigrationBtn" class="secondary" style="width:100%;margin-top:7px" disabled>Restore Pre-migration Content as New Revision</button>';migration.appendChild(block);$('refreshMigrationHistoryBtn').addEventListener('click',loadHistory);$('restorePreMigrationBtn').addEventListener('click',restore);var family=$('componentFamilySelect');if(family)family.addEventListener('change',function(){pendingRecovery=null;loadHistory();});}
  function bind(){inject();setTimeout(loadHistory,0);var meta=$('designMeta');if(meta&&window.MutationObserver)new MutationObserver(function(){if(pendingRecovery){pendingRecovery=null;var button=$('restorePreMigrationBtn');if(button)button.disabled=true;var detail=$('migrationOperationsDetail');if(detail)detail.textContent='Design state changed. Preview recovery again before restoring.';}}).observe(meta,{childList:true,subtree:true});}
  bind();
})();
</script>`;
  html = injectBefore(html, "</body>", script);
  return html;
}
