import { creativeStudioLayerManagerHtml } from "./creativeStudioLayerManagerHtml.js";

function injectBefore(html: string, marker: string, content: string): string {
  if (!html.includes(marker)) throw new Error(`CREATIVE_STUDIO_COMPONENTS_MARKER_MISSING: ${marker}`);
  return html.replace(marker, `${content}${marker}`);
}

export function creativeStudioComponentsHtml(): string {
  let html = creativeStudioLayerManagerHtml();

  const style = `<style>
    #componentLibrary select{width:100%;border:1px solid var(--line);background:#111315;color:var(--text);border-radius:8px;padding:8px;margin-bottom:6px}
    #componentLibrary .component-meta{font-size:10px;color:var(--muted);line-height:1.45;margin:7px 0}
    #componentLibrary .component-status{display:inline-block;padding:2px 6px;border:1px solid var(--line);border-radius:999px;font-size:9px;margin-left:5px}
    #componentLibrary button:disabled{opacity:.38;cursor:not-allowed}
  </style>`;
  html = injectBefore(html, "</head>", style);

  const script = `<script>
(function(){
  'use strict';
  var families=[],lastDesignId=null,refreshing=false;
  function $(id){return document.getElementById(id);}
  function esc(value){return String(value==null?'':value).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c];});}
  function project(){return window.__creativeStudioCurrentProject&&window.__creativeStudioCurrentProject();}
  function primary(){return window.__creativeStudioSelectedLayer&&window.__creativeStudioSelectedLayer();}
  function selection(){var ids=window.__creativeStudioMultiSelectionIds?window.__creativeStudioMultiSelectionIds():[];if(ids.length)return ids;var layer=primary();return layer?[layer.id]:[];}
  function setSelection(ids){return window.__creativeStudioSetMultiSelection?window.__creativeStudioSetMultiSelection(ids):ids;}
  function status(message,type){if(window.__creativeStudioSetStatus)window.__creativeStudioSetStatus(message,type);}
  async function api(path,options){var response=await fetch(path,Object.assign({headers:{'content-type':'application/json'}},options||{}));var data=await response.json();if(!response.ok)throw new Error(data.error||('HTTP '+response.status));return data;}
  function doc(){var p=project();return p&&p.document;}
  function byId(id){var d=doc();return d&&d.layers.find(function(layer){return layer.id===id;});}
  function selectedGroup(){var layers=selection().map(byId).filter(Boolean);return layers.length===1&&layers[0].type==='group'?layers[0]:null;}
  function selectedInstance(){var group=selectedGroup();return group&&group.componentInstance&&group.componentInstance.templateLayerId==='group-root'?group:null;}
  function slug(value){var out=String(value||'block').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,60);return out||'block';}
  function selectedFamily(){var select=$('componentFamilySelect');return select?families.find(function(family){return family.familyId===select.value;}):null;}
  function selectedVersion(){var family=selectedFamily(),select=$('componentVersionSelect');return family&&select?family.versions.find(function(version){return version.id===select.value;}):null;}
  function familyForComponent(componentId){return families.find(function(family){return family.versions.some(function(version){return version.id===componentId;});});}
  function versionForComponent(family,componentId){return family&&family.versions.find(function(version){return version.id===componentId;});}
  function renderVersions(){var family=selectedFamily(),select=$('componentVersionSelect');if(!select)return;var current=select.value;select.innerHTML='<option value="">Choose version…</option>'+(family?family.versions.map(function(version){return '<option value="'+esc(version.id)+'">v'+version.version+(version.isLatest?' · latest':'')+'</option>';}).join(''):'');if(family&&family.versions.some(function(version){return version.id===current;}))select.value=current;else if(family)select.value=family.latestComponentId;}
  function render(){var familySelect=$('componentFamilySelect'),meta=$('componentMeta'),save=$('saveComponentBtn'),insert=$('insertComponentBtn'),duplicate=$('newComponentVersionBtn'),deprecate=$('deprecateComponentBtn'),archive=$('archiveComponentBtn'),reactivate=$('reactivateComponentBtn'),upgrade=$('upgradeComponentInstanceBtn'),detach=$('detachComponentInstanceBtn');if(!familySelect)return;var current=familySelect.value;familySelect.innerHTML='<option value="">Choose component family…</option>'+families.map(function(family){return '<option value="'+esc(family.familyId)+'">'+esc(family.name)+' · '+family.status+'</option>';}).join('');if(families.some(function(family){return family.familyId===current;}))familySelect.value=current;var family=selectedFamily();renderVersions();var version=selectedVersion(),instance=selectedInstance(),instanceFamily=instance?familyForComponent(instance.componentInstance.componentId):null,currentInstanceVersion=instanceFamily?versionForComponent(instanceFamily,instance.componentInstance.componentId):null;var active=family&&family.status==='ACTIVE';save.disabled=!selectedGroup()||Boolean(instance);insert.disabled=!(active&&version);duplicate.disabled=!(active&&version);deprecate.disabled=!(family&&family.status==='ACTIVE');archive.disabled=!(family&&family.status!=='ARCHIVED');reactivate.disabled=!(family&&family.status!=='ACTIVE');detach.disabled=!instance;upgrade.disabled=!(instance&&instanceFamily&&instanceFamily.status==='ACTIVE'&&currentInstanceVersion&&instanceFamily.latestVersion>currentInstanceVersion.version);if(!meta)return;if(family&&version){meta.innerHTML='<strong>'+esc(family.name)+'</strong><span class="component-status">'+family.status+'</span><br>v'+version.version+' · '+version.templateCount+' native layers · '+(version.requiredTruthKeys.length?('requires confirmed '+esc(version.requiredTruthKeys.join(', '))):'no detected factual dependencies')+'<br>latest v'+family.latestVersion+(instance?'<br>selected instance: '+esc(instance.componentInstance.instanceId)+' · '+(currentInstanceVersion?('v'+currentInstanceVersion.version):'legacy version'):'');}else meta.textContent='Blocks store structure/style only. Source campaign text, layer names and asset-backed imagery are never copied into the library.';}
  async function refresh(force){var d=doc();if(!d){families=[];lastDesignId=null;render();return;}if(refreshing)return;if(!force&&lastDesignId===d.id&&families.length)return;refreshing=true;try{var result=await api('/api/studio/components?designId='+encodeURIComponent(d.id));families=result.families||[];lastDesignId=d.id;render();}catch(error){status(error.message,'error');}finally{refreshing=false;}}
  async function saveSelected(){var d=doc(),group=selectedGroup();if(!d||!group||selectedInstance())return;var name=window.prompt('Reusable component family name',group.name);if(name==null||!name.trim())return;var componentId=slug(name)+'-'+Date.now();try{status('Saving immutable structure/style component…');await api('/api/studio/components/create',{method:'POST',body:JSON.stringify({designId:d.id,groupLayerId:group.id,componentId:componentId,name:name.trim()})});await refresh(true);$('componentFamilySelect').value=componentId;render();status('Reusable component family saved as v1 without source campaign copy or asset-backed imagery.','ok');}catch(error){status(error.message,'error');}}
  async function insertSelected(){var d=doc(),family=selectedFamily(),version=selectedVersion();if(!d||!family||family.status!=='ACTIVE'||!version)return;var instanceId='component-'+Date.now();try{status('Validating destination truth and inserting component version…');var result=await api('/api/studio/components/instantiate',{method:'POST',body:JSON.stringify({designId:d.id,componentId:version.id,instanceId:instanceId})});window.__creativeStudioLoadProject(result.project);setSelection([result.instanceGroupId]);render();status('Reusable component inserted with destination text rebinding.','ok');}catch(error){status(error.message,'error');}}
  async function duplicateVersion(){var d=doc(),family=selectedFamily(),version=selectedVersion();if(!d||!family||family.status!=='ACTIVE'||!version)return;try{status('Creating immutable next component version…');var result=await api('/api/studio/components/version',{method:'POST',body:JSON.stringify({designId:d.id,componentId:version.id})});await refresh(true);$('componentFamilySelect').value=result.family.familyId;render();status('New immutable component version created. Existing instances were not changed.','ok');}catch(error){status(error.message,'error');}}
  async function setFamilyStatus(nextStatus){var d=doc(),family=selectedFamily();if(!d||!family)return;try{await api('/api/studio/components/status',{method:'POST',body:JSON.stringify({designId:d.id,familyId:family.familyId,status:nextStatus})});await refresh(true);$('componentFamilySelect').value=family.familyId;render();status('Component family status changed to '+nextStatus+'. Existing instances remain unchanged.','ok');}catch(error){status(error.message,'error');}}
  async function detachInstance(){var d=doc(),instance=selectedInstance();if(!d||!instance)return;var instanceId=instance.componentInstance.instanceId;try{status('Detaching component provenance from selected instance…');var result=await api('/api/studio/components/detach',{method:'POST',body:JSON.stringify({designId:d.id,instanceId:instanceId})});window.__creativeStudioLoadProject(result.project);setSelection([instance.id]);render();status('Instance detached into ordinary native layers in one revision.','ok');}catch(error){status(error.message,'error');}}
  async function upgradeInstance(){var d=doc(),instance=selectedInstance();if(!d||!instance)return;var family=familyForComponent(instance.componentInstance.componentId);if(!family||family.status!=='ACTIVE')return;var current=versionForComponent(family,instance.componentInstance.componentId);if(!current||family.latestVersion<=current.version)return;try{status('Revalidating destination truth and upgrading selected component instance…');var result=await api('/api/studio/components/upgrade',{method:'POST',body:JSON.stringify({designId:d.id,instanceId:instance.componentInstance.instanceId,targetComponentId:family.latestComponentId})});window.__creativeStudioLoadProject(result.project);setSelection([result.instanceGroupId]);await refresh(true);render();status('Component instance upgraded from v'+result.fromVersion+' to v'+result.toVersion+' in one revision.','ok');}catch(error){status(error.message,'error');}}
  function inject(){var panel=$('arrangePanel');if(!panel||$('componentLibrary'))return;var block=document.createElement('div');block.id='componentLibrary';block.className='section';block.style.marginTop='14px';block.innerHTML='<h3>Reusable Components</h3><select id="componentFamilySelect"><option value="">Choose component family…</option></select><select id="componentVersionSelect"><option value="">Choose version…</option></select><div id="componentMeta" class="component-meta">Components are immutable and truth-safe.</div><div class="toolbar-row"><button id="saveComponentBtn" class="secondary" disabled>Save Group as New Family</button><button id="insertComponentBtn" class="secondary" disabled>Insert Version</button></div><button id="newComponentVersionBtn" class="secondary" style="width:100%;margin-top:5px" disabled>Duplicate as New Version</button><div class="toolbar-row"><button id="deprecateComponentBtn" class="secondary" disabled>Deprecate</button><button id="archiveComponentBtn" class="secondary" disabled>Archive</button><button id="reactivateComponentBtn" class="secondary" disabled>Reactivate</button></div><div class="toolbar-row"><button id="upgradeComponentInstanceBtn" class="secondary" disabled>Upgrade Selected Instance</button><button id="detachComponentInstanceBtn" class="secondary" disabled>Detach Instance</button></div><button id="refreshComponentsBtn" class="secondary" style="width:100%;margin-top:5px">Refresh Library</button><div class="note" style="margin-top:7px">No instance auto-updates. Upgrade revalidates destination truth and creates one new design revision; detach removes only component provenance.</div>';panel.appendChild(block);$('componentFamilySelect').addEventListener('change',function(){renderVersions();render();});$('componentVersionSelect').addEventListener('change',render);$('saveComponentBtn').addEventListener('click',saveSelected);$('insertComponentBtn').addEventListener('click',insertSelected);$('newComponentVersionBtn').addEventListener('click',duplicateVersion);$('deprecateComponentBtn').addEventListener('click',function(){setFamilyStatus('DEPRECATED');});$('archiveComponentBtn').addEventListener('click',function(){setFamilyStatus('ARCHIVED');});$('reactivateComponentBtn').addEventListener('click',function(){setFamilyStatus('ACTIVE');});$('upgradeComponentInstanceBtn').addEventListener('click',upgradeInstance);$('detachComponentInstanceBtn').addEventListener('click',detachInstance);$('refreshComponentsBtn').addEventListener('click',function(){refresh(true);});}
  function bind(){inject();document.addEventListener('click',function(){setTimeout(render,0);},true);var meta=$('designMeta');if(meta&&window.MutationObserver)new MutationObserver(function(){var d=doc();if(d&&d.id!==lastDesignId)refresh(true);else render();}).observe(meta,{childList:true,subtree:true});setTimeout(function(){refresh(true);render();},0);}
  bind();
})();
</script>`;
  html = injectBefore(html, "</body>", script);
  return html;
}
