import { creativeStudioFormattedHtml } from "./creativeStudioFormattedHtml.js";

function injectBefore(html: string, marker: string, content: string): string {
  if (!html.includes(marker)) throw new Error(`CREATIVE_STUDIO_TRANSFORM_MARKER_MISSING: ${marker}`);
  return html.replace(marker, `${content}${marker}`);
}

export function creativeStudioTransformHtml(): string {
  let html = creativeStudioFormattedHtml();
  const script = `<script>
(function(){
  'use strict';
  var NS='http://www.w3.org/2000/svg';
  var observer=null,raf=0,gesture=null;
  function $(id){return document.getElementById(id);}
  function project(){return window.__creativeStudioCurrentProject&&window.__creativeStudioCurrentProject();}
  function selected(){return window.__creativeStudioSelectedLayer&&window.__creativeStudioSelectedLayer();}
  function status(message,type){if(window.__creativeStudioSetStatus)window.__creativeStudioSetStatus(message,type);}
  async function api(path,options){var response=await fetch(path,Object.assign({headers:{'content-type':'application/json'}},options||{}));var data=await response.json();if(!response.ok)throw new Error(data.error||('HTTP '+response.status));return data;}
  function svgPoint(event){var svg=$('artboard');var point=svg.createSVGPoint();point.x=event.clientX;point.y=event.clientY;var matrix=svg.getScreenCTM();if(!matrix)return {x:0,y:0};var value=point.matrixTransform(matrix.inverse());return {x:value.x,y:value.y};}
  function el(name,attrs){var node=document.createElementNS(NS,name);Object.keys(attrs||{}).forEach(function(key){node.setAttribute(key,String(attrs[key]));});return node;}
  function schedule(){if(raf)return;raf=requestAnimationFrame(function(){raf=0;draw();});}
  function watch(){var svg=$('artboard');if(!svg||!window.MutationObserver)return;if(observer)observer.disconnect();observer=new MutationObserver(function(mutations){var onlyControls=mutations.length&&mutations.every(function(m){return m.target&&m.target.id==='studioTransformControls';});if(!onlyControls)schedule();});observer.observe(svg,{childList:true,subtree:true});}
  function draw(){var svg=$('artboard');if(!svg)return;if(observer)observer.disconnect();var old=svg.querySelector('#studioTransformControls');if(old)old.remove();var layer=selected(),p=project();if(!layer||!p||!layer.visible||layer.locked){watch();return;}var size=Math.max(10,p.document.artboard.width/90);var cx=layer.x+layer.width/2,cy=layer.y+layer.height/2;var g=el('g',{id:'studioTransformControls','data-layer-id':layer.id,transform:'rotate('+layer.rotation+' '+cx+' '+cy+')'});g.appendChild(el('rect',{x:layer.x,y:layer.y,width:layer.width,height:layer.height,fill:'none',stroke:'#ffd21a','stroke-width':Math.max(2,size/5),'stroke-dasharray':size+' '+Math.max(4,size/2),'pointer-events':'none'}));var resize=el('rect',{x:layer.x+layer.width-size/2,y:layer.y+layer.height-size/2,width:size,height:size,rx:Math.max(2,size/5),fill:'#ffd21a',stroke:'#171717','stroke-width':Math.max(1,size/8),'data-transform-handle':'resize',style:'cursor:nwse-resize'});g.appendChild(resize);if(layer.type!=='logo'){var stem=Math.max(34,size*3);g.appendChild(el('line',{x1:cx,y1:layer.y,x2:cx,y2:layer.y-stem,stroke:'#ffd21a','stroke-width':Math.max(2,size/6),'pointer-events':'none'}));var rotate=el('circle',{cx:cx,cy:layer.y-stem,r:size*.58,fill:'#ffd21a',stroke:'#171717','stroke-width':Math.max(1,size/8),'data-transform-handle':'rotate',style:'cursor:grab'});g.appendChild(rotate);}svg.appendChild(g);watch();}
  function snapMove(layer,x,y,doc){var tolerance=Math.max(4,doc.artboard.width*.006);var safeX=doc.artboard.width*.05,safeY=doc.artboard.height*.05;var right=doc.artboard.width*.95-layer.width,bottom=doc.artboard.height*.95-layer.height;var centerX=doc.artboard.width/2-layer.width/2,centerY=doc.artboard.height/2-layer.height/2;[safeX,right,centerX].some(function(target){if(Math.abs(x-target)<=tolerance){x=target;return true;}return false;});[safeY,bottom,centerY].some(function(target){if(Math.abs(y-target)<=tolerance){y=target;return true;}return false;});return {x:Math.max(0,Math.min(doc.artboard.width-layer.width,x)),y:Math.max(0,Math.min(doc.artboard.height-layer.height,y))};}
  async function commit(operation,message){var p=project();if(!p)return;try{var next=await api('/api/studio/operation',{method:'POST',body:JSON.stringify({designId:p.document.id,operation:operation})});window.__creativeStudioLoadProject(next);status(message,'ok');}catch(error){status(error.message,'error');schedule();}}
  function begin(event){var handle=event.target&&event.target.getAttribute&&event.target.getAttribute('data-transform-handle');if(!handle)return;var layer=selected(),p=project();if(!layer||!p||layer.locked)return;event.preventDefault();event.stopPropagation();var point=svgPoint(event);gesture={mode:handle,layerId:layer.id,start:point,layer:{x:layer.x,y:layer.y,width:layer.width,height:layer.height,rotation:layer.rotation},artboard:p.document.artboard};if(handle==='rotate'){var cx=layer.x+layer.width/2,cy=layer.y+layer.height/2;gesture.startAngle=Math.atan2(point.y-cy,point.x-cx)*180/Math.PI;gesture.previewRotation=layer.rotation;}else{gesture.previewWidth=layer.width;gesture.previewHeight=layer.height;}document.body.style.cursor=handle==='rotate'?'grabbing':'nwse-resize';}
  function move(event){if(!gesture)return;var point=svgPoint(event),layer=selected();if(!layer||layer.id!==gesture.layerId)return;var controls=$('artboard').querySelector('#studioTransformControls');if(!controls)return;if(gesture.mode==='resize'){var dx=point.x-gesture.start.x,dy=point.y-gesture.start.y;var radians=-(gesture.layer.rotation||0)*Math.PI/180;var localX=Math.cos(radians)*dx-Math.sin(radians)*dy;var localY=Math.sin(radians)*dx+Math.cos(radians)*dy;gesture.previewWidth=Math.max(8,Math.min(gesture.artboard.width-gesture.layer.x,gesture.layer.width+localX));gesture.previewHeight=Math.max(8,Math.min(gesture.artboard.height-gesture.layer.y,gesture.layer.height+localY));var outline=controls.querySelector('rect:not([data-transform-handle])');var handle=controls.querySelector('[data-transform-handle="resize"]');if(outline){outline.setAttribute('width',gesture.previewWidth);outline.setAttribute('height',gesture.previewHeight);}if(handle){var size=Number(handle.getAttribute('width'))||12;handle.setAttribute('x',gesture.layer.x+gesture.previewWidth-size/2);handle.setAttribute('y',gesture.layer.y+gesture.previewHeight-size/2);}}else if(gesture.mode==='rotate'){var cx=gesture.layer.x+gesture.layer.width/2,cy=gesture.layer.y+gesture.layer.height/2;var angle=Math.atan2(point.y-cy,point.x-cx)*180/Math.PI;var rotation=gesture.layer.rotation+(angle-gesture.startAngle);if(event.shiftKey)rotation=Math.round(rotation/15)*15;gesture.previewRotation=Math.round(rotation*10)/10;controls.setAttribute('transform','rotate('+gesture.previewRotation+' '+cx+' '+cy+')');}}
  function end(){if(!gesture)return;var current=gesture;gesture=null;document.body.style.cursor='';if(current.mode==='resize'){commit({type:'RESIZE_LAYER',layerId:current.layerId,width:Math.round(current.previewWidth),height:Math.round(current.previewHeight)},'Layer resized on canvas.');}else{commit({type:'ROTATE_LAYER',layerId:current.layerId,rotation:current.previewRotation},'Layer rotated on canvas.');}}
  function editableTarget(target){return target&&(/^(INPUT|TEXTAREA|SELECT)$/.test(target.tagName)||target.isContentEditable);}
  function keyboard(event){if(editableTarget(event.target)||event.defaultPrevented)return;var layer=selected(),p=project();if(!layer||!p||layer.locked)return;if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(event.key)){event.preventDefault();var amount=event.shiftKey?10:1;var x=layer.x+(event.key==='ArrowLeft'?-amount:event.key==='ArrowRight'?amount:0);var y=layer.y+(event.key==='ArrowUp'?-amount:event.key==='ArrowDown'?amount:0);var snapped=snapMove(layer,x,y,p.document);commit({type:'MOVE_LAYER',layerId:layer.id,x:Math.round(snapped.x),y:Math.round(snapped.y)},'Layer nudged '+(event.shiftKey?'10':'1')+' px.');return;}if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==='d'&&layer.type!=='logo'){event.preventDefault();commit({type:'DUPLICATE_LAYER',layerId:layer.id,newLayerId:layer.id+'-copy-'+Date.now(),offsetX:20,offsetY:20},'Layer duplicated.');return;}if((event.key==='Delete'||event.key==='Backspace')&&layer.type!=='logo'&&layer.type!=='background'){event.preventDefault();commit({type:'DELETE_LAYER',layerId:layer.id},'Layer deleted.');}}
  function bind(){var svg=$('artboard');if(!svg)return;svg.addEventListener('pointerdown',begin,true);document.addEventListener('pointermove',move,true);document.addEventListener('pointerup',end,true);document.addEventListener('keydown',keyboard);watch();schedule();var meta=$('designMeta');if(meta&&window.MutationObserver)new MutationObserver(schedule).observe(meta,{childList:true,subtree:true});}
  bind();
})();
</script>`;
  html = injectBefore(html, "</body>", script);
  return html;
}
